@echo off
echo Starting GKICKS Shop Development Server...
echo Refreshing environment variables...
powershell -Command "$env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','User') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','Machine'); npm.cmd run dev"
pause